<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPMqx1Gv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPMqx1Gv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPMqx1Gv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPMqx1Gv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPMqx1Gv\App_KernelDevDebugContainer([
    'container.build_hash' => 'PMqx1Gv',
    'container.build_id' => '27a452c0',
    'container.build_time' => 1746651347,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPMqx1Gv');
